---
apiVersion: v1
kind: Service
metadata:
  name: ftp
  labels:
    app: ftp
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: ftp
      {{- if and (contains "NodePort" .Values.service.type) .Values.service.externalPort }}
      nodePort: {{ .Values.service.externalPort }}
      {{- end }}
    {{- range $e := until (sub .Values.ftp.passive.portMax .Values.ftp.passive.portMin | add1 | int) }}
    {{- $port:= add $.Values.ftp.passive.portMin . }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: ftp-pasv-{{ $port }}
      {{- if contains "NodePort" $.Values.service.type }}
      nodePort: {{ $port }}
      {{- end }}
    {{- end }}
  selector:
    app: ftp
    release: {{ .Release.Name }}